/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx,jsx,js}"],
  safelist: [
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-3",
    "row-[1]",
    "row-[2]",
    "row-[3]",
    "row-[4]",
    "row-[5]",
    "row-[6]",
    "row-[7]",
    "row-[8]",
    "row-[9]",
    "row-[10]",
    "row-[11]",
    "row-[12]",
    "row-[13]",
    "row-[14]",
    "row-[15]",
    "row-[16]",
    "col-[1]",
    "col-[2]",
    "col-[3]",
    "col-[4]",
    "col-[5]",
    "col-[6]",
    "col-[7]",
    "col-[8]",
    "col-[9]",
    "col-[10]",
    "col-[11]",
    "col-[12]",
    "col-[13]",
    "col-[14]",
    "col-[15]",
    "col-[16]",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("@tailwindcss/forms")],
};
